### ISSUE TITLE
Cannot read property 'context' of null

### ISSUE THREAD

**Issue by ZhijiaCHEN** [Borvik/vscode-postgres#25] opened 2018-06-14 15:20 UTC
Hi,
I got an error saying "Cannot read property 'context' of null" when I tried to add new connections. I am using the version 1.24.0 on Windows.

**Comment by Borvik** [comment] 2018-06-14 15:23
Duplicate of #19 - different message, same cause.

**Comment by ZhijiaCHEN** [comment] 2018-06-14 15:32
I just tried the 1.24.1 release and the bug is still there :(

**Closed** 2018-06-14 20:46 UTC
Labels: duplicate
